apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: foodrush
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 9400
      targetPort: 9400
  type: ClusterIP