apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: foodrush
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
