apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: foodrush
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 9800
      targetPort: 9800
  type: ClusterIP
