apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: foodrush
spec:
  selector:
    app: location
  ports:
    - protocol: TCP
      port: 9500
      targetPort: 9500
  type: ClusterIP