apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: foodrush
spec:
  selector:
    app: delivery
  ports:
    - protocol: TCP
      port: 9300
      targetPort: 9300
  type: ClusterIP