apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: foodrush
spec:
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
