apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth
          image: foodrush48/foodrush-user-auth-service:latest
          ports:
            - containerPort: 9000
          env:
            - name: MONGO_URI_USER_SERVICE
              valueFrom:
                secretKeyRef:
                  name: foodrush-secrets
                  key: MONGO_URI_USER_SERVICE
            - name: USER_PORT
              value: "9000"
            - name: USER_SERVICE_URL
              value: "http://user-auth-service:9000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: foodrush-secrets
                  key: JWT_SECRET
            - name: INTERNAL_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: foodrush-secrets
                  key: INTERNAL_SERVICE_API_KEY
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:9800"
