apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: backend-delivery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9300
          env:
            - name: MONGO_URI_DELIVERY_SERVICE
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: MONGO_URI_DELIVERY_SERVICE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: JWT_EXPIRES_IN
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: NOTIFICATION_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery
  ports:
    - port: 9300
      targetPort: 9300
  type: ClusterIP
