# services/order.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: backend-order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9200
          env:
            - name: MONGO_URI_ORDER_SERVICE
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: MONGO_URI_ORDER_SERVICE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: JWT_EXPIRES_IN
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - port: 9200
      targetPort: 9200
  type: ClusterIP