apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: backend-restaurant-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9100
          env:
            - name: MONGO_URI_RESTAURANT_SERVICE
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: MONGO_URI_RESTAURANT_SERVICE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: JWT_EXPIRES_IN
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant
  ports:
    - port: 9100
      targetPort: 9100
  type: ClusterIP
