apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth
          image: backend-user-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:
            - name: MONGO_URI_USER_SERVICE
              valueFrom:
                secretKeyRef:
                  name: user-auth-secret
                  key: MONGO_URI_USER_SERVICE
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: user-auth-secret
                  key: NOTIFICATION_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-auth-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: user-auth-secret
                  key: JWT_EXPIRES_IN
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
spec:
  selector:
    app: user-auth
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
